[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.152.2"

[[redirects]]
  from = "/tags/"
  to = "/"
  status = 301

[[redirects]]
  from = "/categories/"
  to = "/"
  status = 301
